### PR TITLE
feat: Adds stream status Variable & Polling (+Code Reformat)

### PR DESCRIPTION
**Pull request by Caleb-Wishart**
Added support for stream / record Variables and Polling.
These variables contain the value and string of the different states. 
The table below is a copy of what can be found on the `/descriptors.html` page of a Helo device.
| name | value |
| :--: | :--:  |
| eRRSUninitialized | 0|
| eRRSIdle | 1 |
| eRRSRecording | 2 |
| eRRSFailingInIdle | 3 |
| eRRSFailingInRecord | 4 |
| eRRSShutdown | 5 |

Refactored the code in ES6 format similar to [companion-module-matrox-monarch](https://github.com/bitfocus/companion-module-matrox-monarch)

Added basic support for Polling and Variables to get the current Record and Stream status as variables.
This was done with [API reference](https://gitlab.aja.com/pub/rest_api/-/blob/master/HELO/03_HELO_Commands.md#checking-the-status-of-recording-and-streaming)

Updated requests to use fetch rather than system.emit

NB. Tested the start / stop record actions but not all functionality tested after refactoring due to limited access to a HELO device.
In "theory" it should all work :)

### CODE REVIEW

**Comment by Caleb-Wishart** [comment]
@josephdadams, any chance for a review on this?
(Pinging as you were last contributor)

**Comment by josephdadams** [comment]
Happy to! Give me a couple days

**Comment by Caleb-Wishart** [comment]
All good, thanks for the review, not sure if I had to mentioned someone or something,
First pull for Companion

**Comment by josephdadams** [comment]
Looks great! Want to add Boolean feedbacks for recording and streaming status?

**Comment by josephdadams** [comment]
Be sure to add the node-fetch package to your module using `yarn add node-fetch` and commit your `yarn.lock` file

**Comment by Caleb-Wishart** [comment]
Yep, can add a boolean feedback as well.
Will add node-fetch and do a test to make sure it all compiles.

----
Quick variable summary:
| Variable | Meaning |
| :--: | :-- |
| recorder_status_value | API value of recording |
| recorder_status      | API string of recording |
| recording_status     | Boolean, is device recording, True if recording |

-> streaming variables follow same scheme

edit: Removed recording_status and now using proper feedbacks

**Comment by josephdadams** [comment]
@Caleb-Wishart your last commit - that's a variable of True/False for state. I think that's nice - but I'd like to see an actual feedback where it can style the button a certain color if it's in that state. We call those "Feedbacks" in Companion, and there's a type called Boolean. Here's an example: https://github.com/bitfocus/companion-module-televic-dcerno/blob/master/src/feedbacks.js

You'll have to initialize them as you would variables, and any time you get new data and want to check the feedbacks to see if any buttons should be re-styled, call `this.checkFeedbacks()`

**Comment by Caleb-Wishart** [comment]
> We call those "Feedbacks" in Companion, and there's a type called Boolean. Here's an example: https://github.com/bitfocus/companion-module-televic-dcerno/blob/master/src/feedbacks.js

Thanks for the reference.
I did take a look at them but didn't get to it as I was just going to use the variable equations to get feedback. 

I'll take a look when I get some time. I'll look at setting it up as a preset as well.

**Comment by Caleb-Wishart** [comment]
Created the feedback and set up a preset.

I've also added a small python script that I used for testing as I don't have personal access to a Helo, I tried to replicate the structure based on the API documentation. This script can be purged from merge if it's just considered baggage.

**Comment by josephdadams** [comment]
Great work!

**Pull request merged**
